sudo: false
language: go

os:
  - linux

go:
  - "1.11"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - go get -v -d google.golang.org/grpc
  - go get -v -d -t github.com/golang/protobuf/...
  - curl -L https://github.com/google/protobuf/releases/download/v3.5.1/protoc-3.5.1-linux-x86_64.zip -o /tmp/protoc.zip
  - mkdir -p "$HOME"/protoc
  - unzip /tmp/protoc.zip -d "$HOME"/protoc
  - mkdir -p "$HOME"/src && ln -s "$HOME"/protoc "$HOME"/src/protobuf
  - go get -u github.com/golang/protobuf/protoc-gen-go
  - export PATH=$HOME/protoc/bin:$GOPATH/bin:$PATH
  - go get -d -u

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - PGPORT=5433
    - PGDATABASE=postgres
    - PGUSER=postgres
    - PGPASSWORD=''
    - PGHOST=localhost
    - PGX_TEST_DATABASE=postgres://postgres@127.0.0.1:5433/postgres

install:
  - make protos
  - make protos -C $GOPATH/src/github.com/readystock/pg_query_go
  - ls -a $GOPATH/src/github.com/readystock/pg_query_go
  - make protos -C $GOPATH/src/github.com/readystock/raft
  - ls -a $GOPATH/src/github.com/readystock/raft