sudo: false
language: go

os:
  - linux

go:
  - "1.11"

services:
  - postgresql

addons:
  postgresql: "10"
  apt:
    packages:
      - postgresql-10
      - postgresql-client-10
before_install:
  - sudo sed -i -e '/local.*peer/s/postgres/all/' -e 's/peer\|md5/trust/g' /etc/postgresql/*/main/pg_hba.conf
  - sudo service postgresql restart
  - sleep 1
  - ./setup.sh
  - go get -d -u

before_script:
  - psql -c 'create database travis_ci_test;' -U postgres

env:
  global:
    - PGPORT=5433
    - PGDATABASE=postgres
    - PGUSER=postgres
    - PGPASSWORD=''
    - PGHOST=localhost
    - PGX_TEST_DATABASE=postgres://postgres@127.0.0.1:5433/postgres

install:
  - make protos
  - make protos -C $GOPATH/src/github.com/readystock/pg_query_go
  - make protos -C $GOPATH/src/github.com/readystock/raft