admin_port: 8080
database:
  read_buffer: 256
  advertise_address: 127.0.0.1:5433
cluster:
  deny_connection_if_no_nodes: false
nodes:
  - node_id: 1
    address: 127.0.0.1:5432
    database: ready
    user: postgres
    password: Spring!2016
    shards: 1
  - node_id: 2
    address: 127.0.0.1:5432
    database: ready_one
    user: postgres
    password: Spring!2016
    shards: 2
#  - node_id: 3
#    address: 127.0.0.1:5432
#    database: ready_two
#    user: postgres
#    password: Spring!2016
#    shards: 2
