apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: noah-data-node
  labels:
    app: noah-data-node
spec:
  serviceName: noah
  replicas: 3
  selector:
    matchLabels:
      app: noah-data-node
  template:
    metadata:
      labels:
        app: noah-data-node
  # These are converted to volume claims by the controller
  # and mounted at the paths mentioned above.
  # do not use these in production until ssd GCEPersistentDisk or other ssd pd
  volumeClaimTemplates:
    - metadata:
        name: noah-data-node-storage
      spec:
        accessModes: [ "ReadWriteOnce" ]
        storageClassName: fast
        resources:
          requests:
            storage: 1Gi
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: fast
provisioner: k8s.io/minikube-hostpath
parameters:
  type: pd-ssd
