// Code generated by protoc-gen-go. DO NOT EDIT.
// source: account.proto

package system

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NAccount struct {
	AccountId            uint64   `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NAccount) Reset()         { *m = NAccount{} }
func (m *NAccount) String() string { return proto.CompactTextString(m) }
func (*NAccount) ProtoMessage()    {}
func (*NAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_8e28828dcb8d24f0, []int{0}
}

func (m *NAccount) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NAccount.Unmarshal(m, b)
}
func (m *NAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NAccount.Marshal(b, m, deterministic)
}
func (m *NAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NAccount.Merge(m, src)
}
func (m *NAccount) XXX_Size() int {
	return xxx_messageInfo_NAccount.Size(m)
}
func (m *NAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_NAccount.DiscardUnknown(m)
}

var xxx_messageInfo_NAccount proto.InternalMessageInfo

func (m *NAccount) GetAccountId() uint64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

func init() {
	proto.RegisterType((*NAccount)(nil), "system.NAccount")
}

func init() { proto.RegisterFile("account.proto", fileDescriptor_8e28828dcb8d24f0) }

var fileDescriptor_8e28828dcb8d24f0 = []byte{
	// 81 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x4d, 0x4c, 0x4e, 0xce,
	0x2f, 0xcd, 0x2b, 0xd1, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xae, 0x2c, 0x2e, 0x49,
	0xcd, 0x55, 0xd2, 0xe4, 0xe2, 0xf0, 0x73, 0x84, 0xc8, 0x08, 0xc9, 0x72, 0x71, 0x41, 0x15, 0xc5,
	0x67, 0xa6, 0x48, 0x30, 0x2a, 0x30, 0x6a, 0xb0, 0x04, 0x71, 0x42, 0x45, 0x3c, 0x53, 0x92, 0xd8,
	0xc0, 0x3a, 0x8d, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe5, 0xa0, 0x34, 0x57, 0x4a, 0x00, 0x00,
	0x00,
}
