// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sequences.proto

package system

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type SequenceRangeRequest struct {
	SequenceId           uint64   `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequenceRangeRequest) Reset()         { *m = SequenceRangeRequest{} }
func (m *SequenceRangeRequest) String() string { return proto.CompactTextString(m) }
func (*SequenceRangeRequest) ProtoMessage()    {}
func (*SequenceRangeRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bde3ccf263a58418, []int{0}
}

func (m *SequenceRangeRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceRangeRequest.Unmarshal(m, b)
}
func (m *SequenceRangeRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceRangeRequest.Marshal(b, m, deterministic)
}
func (m *SequenceRangeRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceRangeRequest.Merge(m, src)
}
func (m *SequenceRangeRequest) XXX_Size() int {
	return xxx_messageInfo_SequenceRangeRequest.Size(m)
}
func (m *SequenceRangeRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceRangeRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceRangeRequest proto.InternalMessageInfo

func (m *SequenceRangeRequest) GetSequenceId() uint64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

type SequenceRangeResponse struct {
	SequenceId           uint64   `protobuf:"varint,1,opt,name=sequence_id,json=sequenceId,proto3" json:"sequence_id,omitempty"`
	SequenceName         string   `protobuf:"bytes,2,opt,name=sequence_name,json=sequenceName,proto3" json:"sequence_name,omitempty"`
	Start                uint64   `protobuf:"varint,3,opt,name=start,proto3" json:"start,omitempty"`
	End                  uint64   `protobuf:"varint,4,opt,name=end,proto3" json:"end,omitempty"`
	Offset               uint64   `protobuf:"varint,5,opt,name=offset,proto3" json:"offset,omitempty"`
	Count                uint64   `protobuf:"varint,6,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SequenceRangeResponse) Reset()         { *m = SequenceRangeResponse{} }
func (m *SequenceRangeResponse) String() string { return proto.CompactTextString(m) }
func (*SequenceRangeResponse) ProtoMessage()    {}
func (*SequenceRangeResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bde3ccf263a58418, []int{1}
}

func (m *SequenceRangeResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SequenceRangeResponse.Unmarshal(m, b)
}
func (m *SequenceRangeResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SequenceRangeResponse.Marshal(b, m, deterministic)
}
func (m *SequenceRangeResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SequenceRangeResponse.Merge(m, src)
}
func (m *SequenceRangeResponse) XXX_Size() int {
	return xxx_messageInfo_SequenceRangeResponse.Size(m)
}
func (m *SequenceRangeResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SequenceRangeResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SequenceRangeResponse proto.InternalMessageInfo

func (m *SequenceRangeResponse) GetSequenceId() uint64 {
	if m != nil {
		return m.SequenceId
	}
	return 0
}

func (m *SequenceRangeResponse) GetSequenceName() string {
	if m != nil {
		return m.SequenceName
	}
	return ""
}

func (m *SequenceRangeResponse) GetStart() uint64 {
	if m != nil {
		return m.Start
	}
	return 0
}

func (m *SequenceRangeResponse) GetEnd() uint64 {
	if m != nil {
		return m.End
	}
	return 0
}

func (m *SequenceRangeResponse) GetOffset() uint64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *SequenceRangeResponse) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func init() {
	proto.RegisterType((*SequenceRangeRequest)(nil), "system.SequenceRangeRequest")
	proto.RegisterType((*SequenceRangeResponse)(nil), "system.SequenceRangeResponse")
}

func init() { proto.RegisterFile("sequences.proto", fileDescriptor_bde3ccf263a58418) }

var fileDescriptor_bde3ccf263a58418 = []byte{
	// 200 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x4e, 0x2d, 0x2c,
	0x4d, 0xcd, 0x4b, 0x4e, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2b, 0xae, 0x2c,
	0x2e, 0x49, 0xcd, 0x55, 0x32, 0xe7, 0x12, 0x09, 0x86, 0x4a, 0x05, 0x25, 0xe6, 0xa5, 0xa7, 0x06,
	0x81, 0x38, 0xc5, 0x25, 0x42, 0xf2, 0x5c, 0xdc, 0x30, 0x2d, 0xf1, 0x99, 0x29, 0x12, 0x8c, 0x0a,
	0x8c, 0x1a, 0x2c, 0x41, 0x5c, 0x30, 0x21, 0xcf, 0x14, 0xa5, 0xcd, 0x8c, 0x5c, 0xa2, 0x68, 0x3a,
	0x8b, 0x0b, 0xf2, 0xf3, 0x8a, 0x53, 0x09, 0x6a, 0x15, 0x52, 0xe6, 0xe2, 0x85, 0x2b, 0xc8, 0x4b,
	0xcc, 0x4d, 0x95, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x0c, 0xe2, 0x81, 0x09, 0xfa, 0x25, 0xe6, 0xa6,
	0x0a, 0x89, 0x70, 0xb1, 0x16, 0x97, 0x24, 0x16, 0x95, 0x48, 0x30, 0x83, 0xf5, 0x43, 0x38, 0x42,
	0x02, 0x5c, 0xcc, 0xa9, 0x79, 0x29, 0x12, 0x2c, 0x60, 0x31, 0x10, 0x53, 0x48, 0x8c, 0x8b, 0x2d,
	0x3f, 0x2d, 0xad, 0x38, 0xb5, 0x44, 0x82, 0x15, 0x2c, 0x08, 0xe5, 0x81, 0xf4, 0x27, 0xe7, 0x97,
	0xe6, 0x95, 0x48, 0xb0, 0x41, 0xf4, 0x83, 0x39, 0x46, 0x82, 0x5c, 0xfc, 0x30, 0x47, 0x07, 0xa7,
	0x16, 0x95, 0x65, 0x26, 0xa7, 0x26, 0xb1, 0x81, 0x03, 0xc4, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff,
	0x37, 0x56, 0xed, 0x3a, 0x23, 0x01, 0x00, 0x00,
}
